import type { Metadata } from "next";
import { Instrument_Sans, Iceberg } from "next/font/google";
import "./globals.css";

const instrumentSerif = Instrument_Sans({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const iceberg = Iceberg({
  variable: "--font-iceberg",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSerif.variable} ${iceberg.variable} antialiased dark`}
      >
        {children}
      </body>
    </html>
  );
}
